//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertica.Integration.Perfion.PerfionAPIService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGuid", Namespace="http://perfion.com/", ItemName="guid")]
    [System.SerializableAttribute()]
    internal class ArrayOfGuid : System.Collections.Generic.List<System.Guid> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://perfion.com/", ItemName="int")]
    [System.SerializableAttribute()]
    internal class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://perfion.com/", ConfigurationName="PerfionAPIService.GetDataSoap")]
    internal interface GetDataSoap {
        
        // CODEGEN: Generating message contract since element name query from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/ExecuteQuery", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryResponse ExecuteQuery(Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/ExecuteQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryResponse> ExecuteQueryAsync(Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequest request);
        
        // CODEGEN: Generating message contract since element name searchFeature from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetFilterAsHtml", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlResponse GetFilterAsHtml(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetFilterAsHtml", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlResponse> GetFilterAsHtmlAsync(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequest request);
        
        // CODEGEN: Generating message contract since element name searchFeature from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetFilterAsXml", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlResponse GetFilterAsXml(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetFilterAsXml", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlResponse> GetFilterAsXmlAsync(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequest request);
        
        // CODEGEN: Generating message contract since element name imageIDs from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/CalcImageScale", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleResponse CalcImageScale(Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/CalcImageScale", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleResponse> CalcImageScaleAsync(Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequest request);
        
        // CODEGEN: Generating message contract since element name formNamesAndValuesXml from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/FilterValuesToUrlQueryPart", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartResponse FilterValuesToUrlQueryPart(Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/FilterValuesToUrlQueryPart", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartResponse> FilterValuesToUrlQueryPartAsync(Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequest request);
        
        // CODEGEN: Generating message contract since element name xmlSubmit from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/XmlSubmitToUrlQueryPart", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartResponse XmlSubmitToUrlQueryPart(Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/XmlSubmitToUrlQueryPart", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartResponse> XmlSubmitToUrlQueryPartAsync(Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequest request);
        
        // CODEGEN: Generating message contract since element name shortFormQuery from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/ShortFormToXmlWhereClause", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseResponse ShortFormToXmlWhereClause(Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/ShortFormToXmlWhereClause", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseResponse> ShortFormToXmlWhereClauseAsync(Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequest request);
        
        // CODEGEN: Generating message contract since element name GetLanguagesResult from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetLanguages", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesResponse GetLanguages(Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetLanguages", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesResponse> GetLanguagesAsync(Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequest request);
        
        // CODEGEN: Generating message contract since element name language from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetSelectableFeatures", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesResponse GetSelectableFeatures(Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetSelectableFeatures", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesResponse> GetSelectableFeaturesAsync(Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequest request);
        
        // CODEGEN: Generating message contract since element name itemIDs from namespace http://perfion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetTypesUsedBy", ReplyAction="*")]
        Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByResponse GetTypesUsedBy(Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://perfion.com/GetTypesUsedBy", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByResponse> GetTypesUsedByAsync(Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ExecuteQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteQuery", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequestBody Body;
        
        public ExecuteQueryRequest() {
        }
        
        public ExecuteQueryRequest(Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class ExecuteQueryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public ExecuteQueryRequestBody() {
        }
        
        public ExecuteQueryRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ExecuteQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteQueryResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryResponseBody Body;
        
        public ExecuteQueryResponse() {
        }
        
        public ExecuteQueryResponse(Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class ExecuteQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteQueryResult;
        
        public ExecuteQueryResponseBody() {
        }
        
        public ExecuteQueryResponseBody(string ExecuteQueryResult) {
            this.ExecuteQueryResult = ExecuteQueryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFilterAsHtmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilterAsHtml", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequestBody Body;
        
        public GetFilterAsHtmlRequest() {
        }
        
        public GetFilterAsHtmlRequest(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class GetFilterAsHtmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid filterID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string searchFeature;
        
        public GetFilterAsHtmlRequestBody() {
        }
        
        public GetFilterAsHtmlRequestBody(System.Guid filterID, string searchFeature) {
            this.filterID = filterID;
            this.searchFeature = searchFeature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFilterAsHtmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilterAsHtmlResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlResponseBody Body;
        
        public GetFilterAsHtmlResponse() {
        }
        
        public GetFilterAsHtmlResponse(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class GetFilterAsHtmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFilterAsHtmlResult;
        
        public GetFilterAsHtmlResponseBody() {
        }
        
        public GetFilterAsHtmlResponseBody(string GetFilterAsHtmlResult) {
            this.GetFilterAsHtmlResult = GetFilterAsHtmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFilterAsXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilterAsXml", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequestBody Body;
        
        public GetFilterAsXmlRequest() {
        }
        
        public GetFilterAsXmlRequest(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class GetFilterAsXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid filterID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string searchFeature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string language;
        
        public GetFilterAsXmlRequestBody() {
        }
        
        public GetFilterAsXmlRequestBody(System.Guid filterID, string searchFeature, string language) {
            this.filterID = filterID;
            this.searchFeature = searchFeature;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFilterAsXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilterAsXmlResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlResponseBody Body;
        
        public GetFilterAsXmlResponse() {
        }
        
        public GetFilterAsXmlResponse(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class GetFilterAsXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFilterAsXmlResult;
        
        public GetFilterAsXmlResponseBody() {
        }
        
        public GetFilterAsXmlResponseBody(string GetFilterAsXmlResult) {
            this.GetFilterAsXmlResult = GetFilterAsXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class CalcImageScaleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcImageScale", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequestBody Body;
        
        public CalcImageScaleRequest() {
        }
        
        public CalcImageScaleRequest(Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class CalcImageScaleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int maxWidth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int maxHeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Vertica.Integration.Perfion.PerfionAPIService.ArrayOfGuid imageIDs;
        
        public CalcImageScaleRequestBody() {
        }
        
        public CalcImageScaleRequestBody(int maxWidth, int maxHeight, Vertica.Integration.Perfion.PerfionAPIService.ArrayOfGuid imageIDs) {
            this.maxWidth = maxWidth;
            this.maxHeight = maxHeight;
            this.imageIDs = imageIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class CalcImageScaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcImageScaleResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleResponseBody Body;
        
        public CalcImageScaleResponse() {
        }
        
        public CalcImageScaleResponse(Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class CalcImageScaleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float CalcImageScaleResult;
        
        public CalcImageScaleResponseBody() {
        }
        
        public CalcImageScaleResponseBody(float CalcImageScaleResult) {
            this.CalcImageScaleResult = CalcImageScaleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class FilterValuesToUrlQueryPartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilterValuesToUrlQueryPart", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequestBody Body;
        
        public FilterValuesToUrlQueryPartRequest() {
        }
        
        public FilterValuesToUrlQueryPartRequest(Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class FilterValuesToUrlQueryPartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string formNamesAndValuesXml;
        
        public FilterValuesToUrlQueryPartRequestBody() {
        }
        
        public FilterValuesToUrlQueryPartRequestBody(string formNamesAndValuesXml) {
            this.formNamesAndValuesXml = formNamesAndValuesXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class FilterValuesToUrlQueryPartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilterValuesToUrlQueryPartResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartResponseBody Body;
        
        public FilterValuesToUrlQueryPartResponse() {
        }
        
        public FilterValuesToUrlQueryPartResponse(Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class FilterValuesToUrlQueryPartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FilterValuesToUrlQueryPartResult;
        
        public FilterValuesToUrlQueryPartResponseBody() {
        }
        
        public FilterValuesToUrlQueryPartResponseBody(string FilterValuesToUrlQueryPartResult) {
            this.FilterValuesToUrlQueryPartResult = FilterValuesToUrlQueryPartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class XmlSubmitToUrlQueryPartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlSubmitToUrlQueryPart", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequestBody Body;
        
        public XmlSubmitToUrlQueryPartRequest() {
        }
        
        public XmlSubmitToUrlQueryPartRequest(Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class XmlSubmitToUrlQueryPartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlSubmit;
        
        public XmlSubmitToUrlQueryPartRequestBody() {
        }
        
        public XmlSubmitToUrlQueryPartRequestBody(string xmlSubmit) {
            this.xmlSubmit = xmlSubmit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class XmlSubmitToUrlQueryPartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlSubmitToUrlQueryPartResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartResponseBody Body;
        
        public XmlSubmitToUrlQueryPartResponse() {
        }
        
        public XmlSubmitToUrlQueryPartResponse(Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class XmlSubmitToUrlQueryPartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlSubmitToUrlQueryPartResult;
        
        public XmlSubmitToUrlQueryPartResponseBody() {
        }
        
        public XmlSubmitToUrlQueryPartResponseBody(string XmlSubmitToUrlQueryPartResult) {
            this.XmlSubmitToUrlQueryPartResult = XmlSubmitToUrlQueryPartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ShortFormToXmlWhereClauseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShortFormToXmlWhereClause", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequestBody Body;
        
        public ShortFormToXmlWhereClauseRequest() {
        }
        
        public ShortFormToXmlWhereClauseRequest(Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class ShortFormToXmlWhereClauseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shortFormQuery;
        
        public ShortFormToXmlWhereClauseRequestBody() {
        }
        
        public ShortFormToXmlWhereClauseRequestBody(string shortFormQuery) {
            this.shortFormQuery = shortFormQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ShortFormToXmlWhereClauseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShortFormToXmlWhereClauseResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseResponseBody Body;
        
        public ShortFormToXmlWhereClauseResponse() {
        }
        
        public ShortFormToXmlWhereClauseResponse(Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class ShortFormToXmlWhereClauseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShortFormToXmlWhereClauseResult;
        
        public ShortFormToXmlWhereClauseResponseBody() {
        }
        
        public ShortFormToXmlWhereClauseResponseBody(string ShortFormToXmlWhereClauseResult) {
            this.ShortFormToXmlWhereClauseResult = ShortFormToXmlWhereClauseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetLanguagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLanguages", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequestBody Body;
        
        public GetLanguagesRequest() {
        }
        
        public GetLanguagesRequest(Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetLanguagesRequestBody {
        
        public GetLanguagesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetLanguagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLanguagesResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesResponseBody Body;
        
        public GetLanguagesResponse() {
        }
        
        public GetLanguagesResponse(Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class GetLanguagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLanguagesResult;
        
        public GetLanguagesResponseBody() {
        }
        
        public GetLanguagesResponseBody(string GetLanguagesResult) {
            this.GetLanguagesResult = GetLanguagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSelectableFeaturesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSelectableFeatures", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequestBody Body;
        
        public GetSelectableFeaturesRequest() {
        }
        
        public GetSelectableFeaturesRequest(Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class GetSelectableFeaturesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string language;
        
        public GetSelectableFeaturesRequestBody() {
        }
        
        public GetSelectableFeaturesRequestBody(string language) {
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSelectableFeaturesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSelectableFeaturesResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesResponseBody Body;
        
        public GetSelectableFeaturesResponse() {
        }
        
        public GetSelectableFeaturesResponse(Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class GetSelectableFeaturesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSelectableFeaturesResult;
        
        public GetSelectableFeaturesResponseBody() {
        }
        
        public GetSelectableFeaturesResponseBody(string GetSelectableFeaturesResult) {
            this.GetSelectableFeaturesResult = GetSelectableFeaturesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetTypesUsedByRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTypesUsedBy", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequestBody Body;
        
        public GetTypesUsedByRequest() {
        }
        
        public GetTypesUsedByRequest(Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class GetTypesUsedByRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.ArrayOfInt itemIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string language;
        
        public GetTypesUsedByRequestBody() {
        }
        
        public GetTypesUsedByRequestBody(Vertica.Integration.Perfion.PerfionAPIService.ArrayOfInt itemIDs, string language) {
            this.itemIDs = itemIDs;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetTypesUsedByResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTypesUsedByResponse", Namespace="http://perfion.com/", Order=0)]
        public Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByResponseBody Body;
        
        public GetTypesUsedByResponse() {
        }
        
        public GetTypesUsedByResponse(Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://perfion.com/")]
    internal partial class GetTypesUsedByResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTypesUsedByResult;
        
        public GetTypesUsedByResponseBody() {
        }
        
        public GetTypesUsedByResponseBody(string GetTypesUsedByResult) {
            this.GetTypesUsedByResult = GetTypesUsedByResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface GetDataSoapChannel : Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class GetDataSoapClient : System.ServiceModel.ClientBase<Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap>, Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap {
        
        public GetDataSoapClient() {
        }
        
        public GetDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.ExecuteQuery(Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequest request) {
            return base.Channel.ExecuteQuery(request);
        }
        
        public string ExecuteQuery(string query) {
            Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequestBody();
            inValue.Body.query = query;
            Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).ExecuteQuery(inValue);
            return retVal.Body.ExecuteQueryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.ExecuteQueryAsync(Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequest request) {
            return base.Channel.ExecuteQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryResponse> ExecuteQueryAsync(string query) {
            Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.ExecuteQueryRequestBody();
            inValue.Body.query = query;
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).ExecuteQueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetFilterAsHtml(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequest request) {
            return base.Channel.GetFilterAsHtml(request);
        }
        
        public string GetFilterAsHtml(System.Guid filterID, string searchFeature) {
            Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequestBody();
            inValue.Body.filterID = filterID;
            inValue.Body.searchFeature = searchFeature;
            Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetFilterAsHtml(inValue);
            return retVal.Body.GetFilterAsHtmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetFilterAsHtmlAsync(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequest request) {
            return base.Channel.GetFilterAsHtmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlResponse> GetFilterAsHtmlAsync(System.Guid filterID, string searchFeature) {
            Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsHtmlRequestBody();
            inValue.Body.filterID = filterID;
            inValue.Body.searchFeature = searchFeature;
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetFilterAsHtmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetFilterAsXml(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequest request) {
            return base.Channel.GetFilterAsXml(request);
        }
        
        public string GetFilterAsXml(System.Guid filterID, string searchFeature, string language) {
            Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequestBody();
            inValue.Body.filterID = filterID;
            inValue.Body.searchFeature = searchFeature;
            inValue.Body.language = language;
            Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetFilterAsXml(inValue);
            return retVal.Body.GetFilterAsXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetFilterAsXmlAsync(Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequest request) {
            return base.Channel.GetFilterAsXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlResponse> GetFilterAsXmlAsync(System.Guid filterID, string searchFeature, string language) {
            Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetFilterAsXmlRequestBody();
            inValue.Body.filterID = filterID;
            inValue.Body.searchFeature = searchFeature;
            inValue.Body.language = language;
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetFilterAsXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.CalcImageScale(Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequest request) {
            return base.Channel.CalcImageScale(request);
        }
        
        public float CalcImageScale(int maxWidth, int maxHeight, Vertica.Integration.Perfion.PerfionAPIService.ArrayOfGuid imageIDs) {
            Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequestBody();
            inValue.Body.maxWidth = maxWidth;
            inValue.Body.maxHeight = maxHeight;
            inValue.Body.imageIDs = imageIDs;
            Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).CalcImageScale(inValue);
            return retVal.Body.CalcImageScaleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.CalcImageScaleAsync(Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequest request) {
            return base.Channel.CalcImageScaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleResponse> CalcImageScaleAsync(int maxWidth, int maxHeight, Vertica.Integration.Perfion.PerfionAPIService.ArrayOfGuid imageIDs) {
            Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.CalcImageScaleRequestBody();
            inValue.Body.maxWidth = maxWidth;
            inValue.Body.maxHeight = maxHeight;
            inValue.Body.imageIDs = imageIDs;
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).CalcImageScaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.FilterValuesToUrlQueryPart(Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequest request) {
            return base.Channel.FilterValuesToUrlQueryPart(request);
        }
        
        public string FilterValuesToUrlQueryPart(string formNamesAndValuesXml) {
            Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequestBody();
            inValue.Body.formNamesAndValuesXml = formNamesAndValuesXml;
            Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).FilterValuesToUrlQueryPart(inValue);
            return retVal.Body.FilterValuesToUrlQueryPartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.FilterValuesToUrlQueryPartAsync(Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequest request) {
            return base.Channel.FilterValuesToUrlQueryPartAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartResponse> FilterValuesToUrlQueryPartAsync(string formNamesAndValuesXml) {
            Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.FilterValuesToUrlQueryPartRequestBody();
            inValue.Body.formNamesAndValuesXml = formNamesAndValuesXml;
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).FilterValuesToUrlQueryPartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.XmlSubmitToUrlQueryPart(Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequest request) {
            return base.Channel.XmlSubmitToUrlQueryPart(request);
        }
        
        public string XmlSubmitToUrlQueryPart(string xmlSubmit) {
            Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequestBody();
            inValue.Body.xmlSubmit = xmlSubmit;
            Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).XmlSubmitToUrlQueryPart(inValue);
            return retVal.Body.XmlSubmitToUrlQueryPartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.XmlSubmitToUrlQueryPartAsync(Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequest request) {
            return base.Channel.XmlSubmitToUrlQueryPartAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartResponse> XmlSubmitToUrlQueryPartAsync(string xmlSubmit) {
            Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.XmlSubmitToUrlQueryPartRequestBody();
            inValue.Body.xmlSubmit = xmlSubmit;
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).XmlSubmitToUrlQueryPartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.ShortFormToXmlWhereClause(Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequest request) {
            return base.Channel.ShortFormToXmlWhereClause(request);
        }
        
        public string ShortFormToXmlWhereClause(string shortFormQuery) {
            Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequestBody();
            inValue.Body.shortFormQuery = shortFormQuery;
            Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).ShortFormToXmlWhereClause(inValue);
            return retVal.Body.ShortFormToXmlWhereClauseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.ShortFormToXmlWhereClauseAsync(Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequest request) {
            return base.Channel.ShortFormToXmlWhereClauseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseResponse> ShortFormToXmlWhereClauseAsync(string shortFormQuery) {
            Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.ShortFormToXmlWhereClauseRequestBody();
            inValue.Body.shortFormQuery = shortFormQuery;
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).ShortFormToXmlWhereClauseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetLanguages(Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequest request) {
            return base.Channel.GetLanguages(request);
        }
        
        public string GetLanguages() {
            Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequestBody();
            Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetLanguages(inValue);
            return retVal.Body.GetLanguagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetLanguagesAsync(Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequest request) {
            return base.Channel.GetLanguagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesResponse> GetLanguagesAsync() {
            Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetLanguagesRequestBody();
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetLanguagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetSelectableFeatures(Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequest request) {
            return base.Channel.GetSelectableFeatures(request);
        }
        
        public string GetSelectableFeatures(string language) {
            Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequestBody();
            inValue.Body.language = language;
            Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetSelectableFeatures(inValue);
            return retVal.Body.GetSelectableFeaturesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetSelectableFeaturesAsync(Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequest request) {
            return base.Channel.GetSelectableFeaturesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesResponse> GetSelectableFeaturesAsync(string language) {
            Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetSelectableFeaturesRequestBody();
            inValue.Body.language = language;
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetSelectableFeaturesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByResponse Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetTypesUsedBy(Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequest request) {
            return base.Channel.GetTypesUsedBy(request);
        }
        
        public string GetTypesUsedBy(Vertica.Integration.Perfion.PerfionAPIService.ArrayOfInt itemIDs, string language) {
            Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequestBody();
            inValue.Body.itemIDs = itemIDs;
            inValue.Body.language = language;
            Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByResponse retVal = ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetTypesUsedBy(inValue);
            return retVal.Body.GetTypesUsedByResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByResponse> Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap.GetTypesUsedByAsync(Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequest request) {
            return base.Channel.GetTypesUsedByAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByResponse> GetTypesUsedByAsync(Vertica.Integration.Perfion.PerfionAPIService.ArrayOfInt itemIDs, string language) {
            Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequest inValue = new Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequest();
            inValue.Body = new Vertica.Integration.Perfion.PerfionAPIService.GetTypesUsedByRequestBody();
            inValue.Body.itemIDs = itemIDs;
            inValue.Body.language = language;
            return ((Vertica.Integration.Perfion.PerfionAPIService.GetDataSoap)(this)).GetTypesUsedByAsync(inValue);
        }
    }
}
