//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertica.Integration.Tests.Perfion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Examples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Examples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vertica.Integration.Tests.Perfion.Examples", typeof(Examples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Data totalExecutionTime=&quot;00:00:00.1682599&quot;&gt;
        ///	&lt;Features&gt;
        ///		&lt;Category id=&quot;102&quot; language=&quot;dan&quot; caption=&quot;Kategori&quot; captionAlternative=&quot;&quot; unit=&quot;UnitDAN&quot; abbr=&quot;&quot; group=&quot;Generelt&quot; groupOrder=&quot;0&quot; viewGroup=&quot;&quot; viewGroupOrder=&quot;0&quot; viewOrder=&quot;2147483647&quot; form=&quot;Complex&quot; dataType=&quot;String&quot; /&gt;
        ///		&lt;Category id=&quot;102&quot; language=&quot;en&quot; caption=&quot;Category&quot; captionAlternative=&quot;&quot; unit=&quot;UnitEN&quot; abbr=&quot;&quot; group=&quot;General&quot; groupOrder=&quot;0&quot; viewGroup=&quot;&quot; viewGroupOrder=&quot;0&quot; viewOrder=&quot;2147483647&quot; form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Example1 {
            get {
                return ResourceManager.GetString("Example1", resourceCulture);
            }
        }
    }
}
